import Head from "next/head";
import TodoList from "../component/TodoList/TodoList";
import Info from "../component/Info/Info";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List Blockchain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Info />
        <TodoList />
      </main>
    </div>
  );
}
